#include "debug_settings.hh"


#define BUILDEXP_VISUALDEBUG	   (VISUALDEBUG && true)

////
//	Suboptions
////
#define BUILDEXP_VISUALDEBUG_IS_AREA_BUILDABLE   (BUILDEXP_VISUALDEBUG && false)
#define BUILDEXP_VISUALDEBUG_BUILDABLE_POSITIONS (BUILDEXP_VISUALDEBUG && true)
#define BUILDEXP_VISUALDEBUG_ROOF_GENERATION     (BUILDEXP_VISUALDEBUG && false)
#define BUILDEXP_VISUALDEBUG_DOORS				 (BUILDEXP_VISUALDEBUG && true)