#include "debug_settings.hh"


#define HIPROOFMATRIX_VISUALDEBUG  (VISUALDEBUG && true)

////
//	Suboptions
////
#define HIPROOFMATRIX_VISUALDEBUG_PROJECT_BORDERS	(HIPROOFMATRIX_VISUALDEBUG && true)
#define HIPROOFMATRIX_VISUALDEBUG_COMPUTE_POLYGONS	(HIPROOFMATRIX_VISUALDEBUG && true)